language: cpp

compiler:
  - clang
  - gcc

notifications:
  email: false

git:
  submodules: false

before_install:
  # Prepare compilers
  - echo "yes" | sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main';
  - sudo apt-get update;
  - if [ "$CXX" = "g++" ]; then
      sudo apt-get install g++-4.8 -qq;
      export CXX="g++-4.8" CC="gcc-4.8";
    fi
  - if [ "$CXX" = "clang++" ]; then
      sudo apt-get install libstdc++-4.8-dev;
    fi

before_script:
  - cmake .

script:
  - make -j 4
